### ISSUE TITLE
Hej Henrik,I'm testing your app.I could not find the API key at first 😁Later on I found it, after installing 'Join' on my Android, when I opened joinjoaomgcd.appspot.com/?devices. Maybe a hint in the readme would be nice? I've tested it, and it works with the "speak" flowcard (didn't test the other cards yet).

### ISSUE THREAD

**Issue by PeterKawa** [tregota/homey-join#1]
![Screenshot_20230430-181135_Firefox.jpg](https://user-images.githubusercontent.com/74005072/235363859-e6582268-674d-47ab-807a-77c6a7872a6f.jpg)

**Comment by tregota** [comment]
Hi Peter, yeah, they do make it a bit hard to find. :) I hadn't considered that people might find and install this app before becoming a Join user. I'll add a hint to help future users. Thanks!
