### ISSUE TITLE
App action not showing up in Flow

### ISSUE THREAD

**Issue by mg-dev25** [tregota/homey-join#2]
Hello, it's seems like the app is not working. It install and the API is configure but the action in the flow are not showing up. 

1749eccb-e1e7-4639-9b53-88ef63b6404c

Thanks

**Comment by tregota** [comment]
Hmm strange, there are no conditions for the cards to show up, they should just pop up after install.
So when you click the "Add Card" button, is Join not showing up among the Apps or are there no cards to select or doesn't added cards show up in the flow?
And you are not looking in "When..." or "And..." right?
The app has no cards of those types.

**Comment by mg-dev25** [comment]
Yep I found this morning there was no option for the "when" and "and". I was thinking that the join app allowed to receive command.

We can communicate between tasker and homey using homey API and http, anyway.

Sorry
