### ISSUE TITLE
Join APP Not worjin4

### ISSUE THREAD

**Issue by Dome0068** [tregota/homey-join#3]
Hello Eric,
Starting from today Join app is not able to send any command or notification to my join device.
Until yesterday all worked fine by sending command and notification.
I send a diagnostic report here :7de23da9-7732-48ba-9fe8-9ee73b44f68c
Please let me know

**Comment by tregota** [comment]
Eric? :) 
Thanks for the report, I just now published a new version that should fix it.
Let me know if it still isn't working for you.

**Comment by Dome0068** [comment]
Hello Henrik,

Apologize for mistake.. :)
Thank you very much for the prompted response.
As soon as I can test it tomorrow I will let you know.

Best regards

Domenico


Il gio 5 set 2024, 21:54 tregota ***@***.***> ha scritto:

**Comment by Dome0068** [comment]
Hello Henrik,

After the update to version 1.0.1 it seemed to work back fine again.
But now I am facing the same problem, it is not possible to send any
command or notification again.
I have made a new diagnostic report: 2a443de0-83bd-41a2-8972-31f16503bf6d

Please let me know

Thanks and regards

Domenico


Il giorno gio 5 set 2024 alle ore 22:14 DE ***@***.***> ha scritto:

**Comment by tregota** [comment]
Hi again, Domenico.
Hmm. So it started working again but never managed to send any messages, or did it work for a while and then stop?
Given the diagnostic report, it seems as if the messages are sent without any problem.

The error was caused by google changing something on their end and causeing Join to have to update code which I used so I had to update as well. So if it works via join it should work from this app aswell. I hope. It works for me right now.

When accessing https://joinjoaomgcd.appspot.com/?devices, can you send messages to the device in question from there?

**Comment by Dome0068** [comment]
Hi Henrik,

No it worked for a while and then stop..
I don't know as I have to do now..
Do you have any other suggestion?

Thank you for support

Domenico

Il ven 6 set 2024, 17:29 tregota ***@***.***> ha scritto:

**Comment by tregota** [comment]
Did you try sending a message via https://joinjoaomgcd.appspot.com/?devices
If it doesn't work using the Join API directly then my app cannot make it work. You'll have to ask for help in the Join forums.
But if it works there then I'll have to debug some more. I can try and send a bunch of messages and see if it stops working for me as well. But make sure to try sending to your device via the link above.

**Comment by Dome0068** [comment]
It seems that your app works sometime for a while and then stop, I have
tried again just now.
But I can confirm that by Join web app you mentioned it works always by
sending all message to my Join device.

Domenico



Il ven 6 set 2024, 17:50 tregota ***@***.***> ha scritto:

**Comment by Dome0068** [comment]
Just to add that I have already tried to send message by Join web app two
days ago when I faced issue in your Homey App and all messages was sent
successfully.
Then after that I opened the issue for your App

Il ven 6 set 2024, 18:00 DE ***@***.***> ha scritto:

**Comment by tregota** [comment]
ok, I'll try to replicate. how often do your flows send messages? and to what kind of device?

**Comment by Dome0068** [comment]
I have created a flow that sends commands by Join notification to an
Android tablet (black view tab11).
I have created several macrodroid macros that process these commands on the
tablet.
So some of these are manual by calling them in Homey App, others are
automatic on logic based in other flows.
I created also a repetition mechanism to send command and it stops when the
command feedback is received from tablet (by using a webhook in Homey) .
This to assure command delivery from Homey to tablet.
In these last days this repetitive mechanism shown errors or too repetions
because of your App stopped to send Join messages

Il ven 6 set 2024, 18:27 tregota ***@***.***> ha scritto:

**Comment by Dome0068** [comment]
At moment for every command every command has repeated every 3 seconds for
a maximum of 10 repetition, theb an alarm will be raised and it stops

Il ven 6 set 2024, 18:37 DE ***@***.***> ha scritto:

**Comment by tregota** [comment]
I've been sending messages constantly to an android device for a few hours and I noticed just now that I stopped getting notifications for a time (around 60 notifications missing) and then after maybe 3 minutes they all showed up at once. I haven't seen any other issue than that, no lost messages. So the problem might be that sometimes Join cannot deliver messages immediatly. If this is what causes your problems then the app is not at fault. It's either Join or Google. You could ask about delayed messages in the Join forums for a better answer if that is what you are seeing aswell.

**Comment by Dome0068** [comment]
Ok Henrik,
If it is not a fault in your App as you confirmed I will try to ask in Join
forum.
In any case this strange behavior appeared only since two or three day ago.
Could be possible that something was changed in Join app or internal
procedures..
Thank you for the good support

Il ven 6 set 2024, 21:16 tregota ***@***.***> ha scritto:
